//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emprestimo
    {
        public int numero_emprestimo { get; set; }
        public Nullable<int> Emp_id_cliente { get; set; }
        public Nullable<int> Emp_livro_ID { get; set; }
        public System.DateTime Data_Emprestimo { get; set; }
        public Nullable<System.DateTime> Data_Devolucao { get; set; }
    
        public virtual livro livro { get; set; }
    }
}
