//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livro()
        {
            this.emprestimos = new HashSet<emprestimo>();
        }
    
        public int livro_ID { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public Nullable<int> ano { get; set; }
        public bool disponivel { get; set; }
        public Nullable<double> preco { get; set; }
        public string fotopath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emprestimo> emprestimos { get; set; }
        public virtual autore autore { get; set; }
    }
}
