//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TI3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_livros
    {
        public int livro_ID { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public Nullable<int> ano { get; set; }
        public bool disponivel { get; set; }
        public Nullable<double> preco { get; set; }
        public string fotopath { get; set; }
        public Nullable<int> total { get; set; }
    }
}
